title: ironPeak status

buildFuture: true

languageCode: en
defaultContentLanguage: en

baseURL: https://status.ironpeak.be

params:
  # These are your systems. Change them to
  # change the amount of components.
  #
  # For help, see the wiki:
  # https://github.com/cstate/cstate/wiki/Customization
  systems:
    - name: Website

  dateFormat: January 2, 2006 at 3:04 PM
  shortDateFormat: 15:04 — Jan 2

  useLargeHeaderDesign: false
  useLogo: true
  logo: /icon.png

  description: We continuously monitor the status of our services and if there are any interruptions, a note will be posted here.

  # Tabs on homepage
  # Uncomment to enable.
  #
  # Format:
  # customTabs:
  #  -
  #    name: Name
  #    link: https://example.com

  # Auto refresh the page
  # every ~5 min
  #
  # This does nothing but
  # refresh the page; it
  # does not send alerts!
  #
  # Default: true
  # BOOLEAN; `true`, `false`
  autoRefresh: true

  incidentPostsPerPage: 10

  brand: "0a0c0f"
  ok: "008000"
  disrupted: "cc4400"
  down: "e60000"
  notice: "24478f"

  alwaysKeepBrandColor: true


theme: cstate

preserveTaxonomyNames: true

taxonomies:
  affected: affected
